# Generated by Django 3.2.8 on 2024-06-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetBaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aset', models.CharField(max_length=255)),
                ('kode_aset', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penyusutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umur_ekonomis', models.PositiveIntegerField()),
                ('aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penyusutan', to='accounts.asetbaru')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembelian', models.DateField()),
                ('toko_distributor', models.CharField(max_length=255)),
                ('no_invoice', models.CharField(max_length=50)),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembelian', to='accounts.asetbaru')),
            ],
        ),
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='lampiran/')),
                ('keterangan', models.TextField(blank=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='accounts.asetbaru')),
            ],
        ),
        migrations.CreateModel(
            name='DetailAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('produsen', models.CharField(max_length=100)),
                ('no_seri_kode_produksi', models.CharField(max_length=50)),
                ('tahun_produksi', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
                ('aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='accounts.asetbaru')),
            ],
        ),
    ]
