# Generated by Django 3.2.8 on 2024-06-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240614_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Category',
        ),
    ]
