# Generated by Django 4.2.13 on 2024-06-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_kategori_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategori',
        ),
    ]
