# Generated by Django 4.2.13 on 2024-06-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_category_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='asetbaru',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
