# Generated by Django 4.2.13 on 2024-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_detailaset_tahun_produksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asetbaru',
            name='kode_aset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
