# Generated by Django 4.2.13 on 2024-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_asetbaru_kode_aset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='harga_total',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Penyusutan',
        ),
    ]
