# Generated by Django 4.2.13 on 2024-06-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pembelian_harga_satuan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenanggungJawab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanggung_jawab', to='accounts.asetbaru')),
            ],
        ),
    ]
