# Generated by Django 4.2.13 on 2024-06-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_penanggungjawab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian',
            old_name='no_invoice',
            new_name='no_kontrak',
        ),
    ]
