# Generated by Django 4.2.13 on 2024-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_tanggal_pembelian_pembelian_tanggal_kontrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='asetbaru',
            name='kondisi_aset',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Rusak Berat', 'Rusak Berat')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
