# Generated by Django 4.2.13 on 2024-06-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_asetbaru_kondisi_aset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosisiAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='asetbaru',
            name='posisi_aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.posisiasset'),
        ),
    ]
