# Generated by Django 4.2.13 on 2024-07-06 06:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_posisiasset_asetbaru_posisi_aset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampiran',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.rename_image),
        ),
    ]
